[2024-09-22T04:45:16.453+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-22T04:45:16.462+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Youtube_dag.tsk_load_to_s3 manual__2024-09-22T04:44:32.262198+00:00 [queued]>
[2024-09-22T04:45:16.468+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Youtube_dag.tsk_load_to_s3 manual__2024-09-22T04:44:32.262198+00:00 [queued]>
[2024-09-22T04:45:16.468+0000] {taskinstance.py:2865} INFO - Starting attempt 3 of 3
[2024-09-22T04:45:16.486+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): tsk_load_to_s3> on 2024-09-22 04:44:32.262198+00:00
[2024-09-22T04:45:16.492+0000] {standard_task_runner.py:72} INFO - Started process 6825 to run task
[2024-09-22T04:45:16.495+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Youtube_dag', 'tsk_load_to_s3', 'manual__2024-09-22T04:44:32.262198+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/youtubeanalytics.py', '--cfg-path', '/tmp/tmpwnvvrllb']
[2024-09-22T04:45:16.497+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask tsk_load_to_s3
[2024-09-22T04:45:16.535+0000] {task_command.py:467} INFO - Running <TaskInstance: Youtube_dag.tsk_load_to_s3 manual__2024-09-22T04:44:32.262198+00:00 [running]> on host ip-172-31-40-65.ap-south-1.compute.internal
[2024-09-22T04:45:16.609+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='bharath19rocks@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Youtube_dag' AIRFLOW_CTX_TASK_ID='tsk_load_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T04:44:32.262198+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-22T04:44:32.262198+00:00'
[2024-09-22T04:45:16.610+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-22T04:45:16.625+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-22T04:45:16.625+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "aws s3 mv {'comment': 'Watch Blockbuster THIRUCHITRAMBALAM worldwide only on SUN NXT. Download the app now\\r\\nAndroid: http://bit.ly/SunNxtAdroid\\r\\niOS: India - http://bit.ly/sunNXT\\r\\niOS Rest of the World - http://bit.ly/ussunnxt', 'num_of_likes': 817, 'publish_time': '2022-10-07T04:59:15Z'} s3://endtoendairflow-bucket/"]
[2024-09-22T04:45:16.635+0000] {subprocess.py:86} INFO - Output:
[2024-09-22T04:45:17.089+0000] {subprocess.py:93} INFO - 
[2024-09-22T04:45:17.089+0000] {subprocess.py:93} INFO - Unknown options: num_of_likes:,817,,publish_time:,2022-10-07T04:59:15Z},s3://endtoendairflow-bucket/
[2024-09-22T04:45:17.152+0000] {subprocess.py:97} INFO - Command exited with return code 255
[2024-09-22T04:45:17.161+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 255.
[2024-09-22T04:45:17.164+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=Youtube_dag, task_id=tsk_load_to_s3, run_id=manual__2024-09-22T04:44:32.262198+00:00, execution_date=20240922T044432, start_date=20240922T044516, end_date=20240922T044517
[2024-09-22T04:45:17.178+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-22T04:45:17.178+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task tsk_load_to_s3 (Bash command failed. The command returned a non-zero exit code 255.; 6825)
Traceback (most recent call last):
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoendairflow_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 255.
[2024-09-22T04:45:17.191+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-22T04:45:17.207+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-22T04:45:17.207+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
